# Generated by Django 4.0.2 on 2022-02-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateTimeField(null=True, verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
