# Generated by Django 4.0.2 on 2022-02-28 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0002_alter_patient_birth_date_alter_patient_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('doc_date', models.IntegerField(default=0)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medapp.case')),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DocumentBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medapp.document')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medapp.patient'),
        ),
    ]
