# Generated by Django 4.0.2 on 2022-03-16 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0003_document_alter_patient_gender_documentbody_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentBody',
        ),
    ]
