# Generated by Django 4.0.2 on 2022-03-17 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0004_delete_documentbody'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('choice_text', models.JSONField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='document',
            old_name='heading',
            new_name='header',
        ),
        migrations.CreateModel(
            name='DocumentBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_filling', models.JSONField(max_length=200)),
                ('doc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medapp.document')),
            ],
        ),
    ]
